import '/imports/startup/client/functions.js';
import './profile.js';
import './login.js';
import './terms.html';
//import './termsfeed-terms-conditions-html-english.html';
import './setup.js';
import './register.js';
import './leave.js';
import './logout.js';
